"""
train_shards.py — Large-Scale 8-Agent Training with Sharded Data

Trains on massive datasets generated by spawner_8.py.

Usage:
    # First, generate data
    python spawner_8.py --n_personas 10000 --n_days 1825 --n_shards 50
    
    # Then train
    python train_shards.py --shard_dir data_shards --epochs 150
"""

import os
import sys
import argparse
import torch
import numpy as np
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from model.model_8 import DRIFT8, build_drift_8
from training.training_8 import Trainer8
from data.shard_loader import ShardLoader
from data.agents_8 import ALL_AGENTS


# Curriculum schedule
CURRICULUM = [
    (0, 30, 1),    # Epoch 0-30: Phase 1 (clean)
    (30, 60, 2),   # Epoch 30-60: Phase 2 (10% dropout)
    (60, 100, 3),  # Epoch 60-100: Phase 3 (20% dropout)
    (100, 130, 4), # Epoch 100-130: Phase 4 (30% dropout)
    (130, 200, 5), # Epoch 130+: Phase 5 (40% dropout)
]


def get_phase(epoch: int) -> int:
    for start, end, phase in CURRICULUM:
        if start <= epoch < end:
            return phase
    return 5


def parse_args():
    parser = argparse.ArgumentParser(description="Large-Scale 8-Agent Training")
    parser.add_argument("--shard_dir", type=str, default="data_shards", help="Shard directory")
    parser.add_argument("--epochs", type=int, default=150)
    parser.add_argument("--batch_size", type=int, default=16)
    parser.add_argument("--lr", type=float, default=3e-4)
    parser.add_argument("--d_model", type=int, default=128)
    parser.add_argument("--device", type=str, default="cuda")
    parser.add_argument("--precision", type=str, default="bf16", choices=["bf16", "fp16", "fp32"])
    parser.add_argument("--checkpoint_dir", type=str, default="checkpoints_8")
    parser.add_argument("--resume", type=str, default=None)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--n_windows", type=int, default=10, help="Windows per sample per epoch")
    parser.add_argument("--val_ratio", type=float, default=0.1)
    return parser.parse_args()


def set_seed(seed: int):
    torch.manual_seed(seed)
    np.random.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def main():
    args = parse_args()
    set_seed(args.seed)
    
    print("="*70)
    print(" LARGE-SCALE 8-AGENT DRIFT TRAINING")
    print("="*70)
    print(f" Shard dir:   {args.shard_dir}")
    print(f" Epochs:      {args.epochs}")
    print(f" Batch size:  {args.batch_size}")
    print(f" LR:          {args.lr}")
    print(f" Model dim:   {args.d_model}")
    print(f" Device:      {args.device}")
    print(f" Precision:   {args.precision}")
    print("="*70)
    
    # Check device
    if args.device == "cuda" and not torch.cuda.is_available():
        print("WARNING: CUDA not available, using CPU")
        args.device = "cpu"
    
    # Check shards exist
    manifest_path = os.path.join(args.shard_dir, "manifest.json")
    if not os.path.exists(manifest_path):
        print(f"\nERROR: No manifest found at {manifest_path}")
        print("Run spawner_8.py first to generate data:")
        print("  python spawner_8.py --n_personas 10000 --n_days 1825 --n_shards 50")
        return
    
    # Create shard loader
    print("\n[1/3] Loading shard metadata...")
    shard_loader = ShardLoader(
        shard_dir=args.shard_dir,
        batch_size=args.batch_size,
        n_windows=args.n_windows,
        val_ratio=args.val_ratio,
    )
    
    # Build model
    print("\n[2/3] Building model...")
    model = build_drift_8(
        d_model=args.d_model,
        precision=args.precision,
    )
    n_params = sum(p.numel() for p in model.parameters())
    print(f"  Parameters: {n_params:,}")
    
    # Create trainer
    print("\n[3/3] Setting up trainer...")
    trainer = Trainer8(
        model=model,
        device=args.device,
        lr=args.lr,
        total_epochs=args.epochs,
        checkpoint_dir=args.checkpoint_dir,
        precision=args.precision,
    )
    
    # Training loop with curriculum
    print("\n" + "="*70)
    print(" STARTING TRAINING")
    print("="*70)
    
    current_phase = -1
    train_loader = None
    val_loader = None
    
    for epoch in range(args.epochs):
        # Check for phase change
        phase = get_phase(epoch)
        if phase != current_phase:
            print(f"\n[curriculum] Epoch {epoch}: switching to Phase {phase}")
            current_phase = phase
            train_loader, val_loader = shard_loader.get_loaders(phase=phase)
        
        # Train epoch
        model.train()
        train_losses = {}
        n_batches = 0
        
        for xb, yb, routing, persona in train_loader:
            xb = xb.to(args.device)
            yb = yb.to(args.device)
            routing = routing.to(args.device)
            
            # Forward pass
            with torch.autocast(
                device_type=args.device,
                dtype=torch.bfloat16 if args.precision == "bf16" else torch.float16,
                enabled=args.precision in ("bf16", "fp16"),
            ):
                outputs = model(xb, return_weights=True, routing_targets=routing)
                
                from training.training_8 import compute_total_loss_8, LossWeights
                weights = trainer._get_loss_weights(epoch, trainer.collapse_history)
                loss, breakdown = compute_total_loss_8(outputs, yb, weights, routing)
            
            # Backward
            trainer.optimizer.zero_grad()
            if args.precision == "fp16":
                trainer.scaler.scale(loss).backward()
                trainer.scaler.unscale_(trainer.optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                trainer.scaler.step(trainer.optimizer)
                trainer.scaler.update()
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                trainer.optimizer.step()
            
            if trainer.scheduler:
                trainer.scheduler.step()
            
            # Track losses
            for k, v in breakdown.__dict__.items():
                if k != "per_agent":
                    train_losses[k] = train_losses.get(k, 0) + v
            n_batches += 1
            
            # Track orthogonality
            trainer.collapse_history.append(breakdown.orthogonality)
            if len(trainer.collapse_history) > 100:
                trainer.collapse_history.pop(0)
        
        train_losses = {k: v / max(1, n_batches) for k, v in train_losses.items()}
        
        # Validation
        model.eval()
        val_losses = {}
        val_batches = 0
        
        with torch.no_grad():
            for xb, yb, routing, persona in val_loader:
                xb = xb.to(args.device)
                yb = yb.to(args.device)
                routing = routing.to(args.device)
                
                with torch.autocast(
                    device_type=args.device,
                    dtype=torch.bfloat16 if args.precision == "bf16" else torch.float16,
                    enabled=args.precision in ("bf16", "fp16"),
                ):
                    outputs = model(xb, return_weights=True)
                    _, breakdown = compute_total_loss_8(outputs, yb, weights, routing)
                
                for k, v in breakdown.__dict__.items():
                    if k != "per_agent":
                        val_losses[k] = val_losses.get(k, 0) + v
                val_batches += 1
        
        val_losses = {k: v / max(1, val_batches) for k, v in val_losses.items()}
        val_loss = val_losses["total"]
        
        # Checkpoint
        is_best = val_loss < trainer.best_val_loss
        if is_best:
            trainer.best_val_loss = val_loss
        
        if epoch % 5 == 0 or is_best:
            trainer.save_checkpoint(epoch, val_loss, is_best)
        
        # Log
        lr = trainer.optimizer.param_groups[0]["lr"]
        print(
            f"Epoch {epoch:3d} | Phase {phase} | "
            f"train={train_losses['total']:.4f} "
            f"(q={train_losses['quantile']:.4f} "
            f"orth={train_losses['orthogonality']:.4f}) | "
            f"val={val_loss:.4f} | lr={lr:.2e}"
        )
    
    print("\n" + "="*70)
    print(" TRAINING COMPLETE")
    print("="*70)
    print(f"Best val loss: {trainer.best_val_loss:.4f}")
    print(f"Checkpoints:   {args.checkpoint_dir}/")
    print("="*70)


if __name__ == "__main__":
    main()
