"""
shard_loader.py — Efficient Sharded Data Loader

Loads data shards generated by spawner_8.py with:
- Lazy loading (only loads needed shards)
- Memory-mapped access
- Curriculum phase support
- Efficient batching

Usage:
    loader = ShardLoader("data_shards/", batch_size=16)
    for X, y, routing, persona_names in loader:
        # train
"""

import os
import json
import torch
import numpy as np
from torch.utils.data import Dataset, DataLoader, IterableDataset
from typing import Dict, List, Optional, Tuple, Iterator
import random

from data.agents_8 import ALL_AGENTS, N_AGENTS, ALL_SIGNALS


TOKEN_DIM = 104  # Same as in loader_8.py


class ShardDataset(IterableDataset):
    """
    Iterable dataset that loads shards on-demand.
    
    Supports:
    - Multiple epochs without re-loading
    - Shuffling across shards
    - Curriculum phases (degradation)
    """
    
    def __init__(
        self,
        shard_dir: str,
        manifest: dict,
        seq_len: int = 90,
        horizons: List[int] = [7, 30, 90, 180],
        n_windows_per_sample: int = 10,
        degradation: Dict[str, float] = None,
        shuffle_shards: bool = True,
        shuffle_windows: bool = True,
    ):
        self.shard_dir = shard_dir
        self.manifest = manifest
        self.seq_len = seq_len
        self.horizons = horizons
        self.n_windows = n_windows_per_sample
        self.degradation = degradation or {"dropout_prob": 0.0, "missing_prob": 0.0}
        self.shuffle_shards = shuffle_shards
        self.shuffle_windows = shuffle_windows
        
        self.n_days = manifest["n_days"]
        self.n_samples = manifest["n_personas"]
        self.shard_paths = [s["path"] for s in manifest["shards"]]
        
        # Cache for loaded shards
        self._shard_cache = {}
        self._cache_size = 3  # Keep 3 shards in memory
    
    def _load_shard(self, shard_idx: int) -> List[dict]:
        """Load a shard (with LRU caching)."""
        if shard_idx in self._shard_cache:
            return self._shard_cache[shard_idx]
        
        # Load shard
        path = os.path.join(self.shard_dir, self.shard_paths[shard_idx])
        data = torch.load(path, map_location="cpu")
        
        # Manage cache
        if len(self._shard_cache) >= self._cache_size:
            # Remove oldest
            oldest = next(iter(self._shard_cache))
            del self._shard_cache[oldest]
        
        self._shard_cache[shard_idx] = data
        return data
    
    def _sample_to_batch(
        self,
        sample: dict,
        start_idx: int,
    ) -> Tuple[torch.Tensor, torch.Tensor, int, str]:
        """Convert sample window to training batch."""
        n_days = sample["t"].shape[0]
        end_idx = min(start_idx + self.seq_len, n_days)
        actual_len = end_idx - start_idx
        
        # Build X
        X = torch.zeros(self.seq_len, TOKEN_DIM)
        
        # Signals (first 11 dims)
        signal_list = list(sample["signals"].keys())
        for i, sig_name in enumerate(signal_list[:11]):
            X[:actual_len, i] = sample["signals"][sig_name][start_idx:end_idx].float()
        
        # Derived features
        for i in range(actual_len):
            idx = start_idx + i
            
            # Rolling means (7-day)
            for j, sig_name in enumerate(signal_list[:5]):
                if idx >= 7:
                    X[i, 11 + j] = sample["signals"][sig_name][idx-7:idx].float().mean()
            
            # Differences
            for j, sig_name in enumerate(signal_list[:5]):
                if idx > 0:
                    X[i, 16 + j] = (sample["signals"][sig_name][idx] - sample["signals"][sig_name][idx-1]).float()
            
            # Rolling stds
            for j, sig_name in enumerate(signal_list[:4]):
                if idx >= 7:
                    X[i, 21 + j] = sample["signals"][sig_name][idx-7:idx].float().std()
            
            # Day features
            X[i, 25] = (idx % 365) / 365.0
            dow = idx % 7
            X[i, 26 + dow] = 1.0
        
        # Apply degradation
        if self.degradation["dropout_prob"] > 0:
            mask = torch.rand(self.seq_len) > self.degradation["dropout_prob"]
            X = X * mask.unsqueeze(1)
        
        # Build y
        y = torch.zeros(N_AGENTS, len(self.horizons))
        for agent_idx, agent_name in enumerate(ALL_AGENTS):
            if agent_name in sample["agent_gts"]:
                gt = sample["agent_gts"][agent_name]["values"]
                for h_idx, h in enumerate(self.horizons):
                    target_idx = start_idx + h
                    if target_idx < n_days:
                        y[agent_idx, h_idx] = gt[target_idx].float()
        
        # Routing target (primary agent)
        routing_target = sample.get("routing_targets", {}).get(
            sample.get("primary_agent", "cardio"), 0
        )
        if isinstance(routing_target, dict):
            routing_target = list(routing_target.values())[0] if routing_target else 0
        routing_target = int(routing_target) if routing_target else 0
        
        persona_name = sample.get("persona_name", "unknown")
        
        return X, y, routing_target, persona_name
    
    def __iter__(self) -> Iterator[Tuple[torch.Tensor, torch.Tensor, int, str]]:
        """Iterate over all samples."""
        shard_order = list(range(len(self.shard_paths)))
        if self.shuffle_shards:
            random.shuffle(shard_order)
        
        for shard_idx in shard_order:
            shard = self._load_shard(shard_idx)
            
            # Sample order within shard
            sample_order = list(range(len(shard)))
            if self.shuffle_windows:
                random.shuffle(sample_order)
            
            for sample_idx in sample_order:
                sample = shard[sample_idx]
                n_days = sample["t"].shape[0]
                
                # Sample random windows
                max_start = n_days - max(self.horizons) - 1
                if max_start < self.seq_len:
                    continue
                
                for _ in range(self.n_windows):
                    start_idx = random.randint(0, max(1, max_start))
                    yield self._sample_to_batch(sample, start_idx)
    
    def __len__(self):
        """Approximate length."""
        return self.n_samples * self.n_windows


class ShardLoader:
    """
    High-level shard loader that creates train/val dataloaders.
    
    Handles:
    - Train/val split (by shard)
    - Curriculum phases
    - Automatic manifest loading
    """
    
    def __init__(
        self,
        shard_dir: str,
        batch_size: int = 16,
        seq_len: int = 90,
        n_windows: int = 10,
        val_ratio: float = 0.1,
        num_workers: int = 0,
        pin_memory: bool = True,
    ):
        self.shard_dir = shard_dir
        self.batch_size = batch_size
        self.seq_len = seq_len
        self.n_windows = n_windows
        self.val_ratio = val_ratio
        self.num_workers = num_workers
        self.pin_memory = pin_memory
        
        # Load manifest
        manifest_path = os.path.join(shard_dir, "manifest.json")
        with open(manifest_path, "r") as f:
            self.manifest = json.load(f)
        
        print(f"[ShardLoader] Loaded manifest: {self.manifest['n_personas']:,} personas, {self.manifest['n_days']} days")
        
        # Split shards
        n_shards = len(self.manifest["shards"])
        n_val = max(1, int(n_shards * val_ratio))
        
        self.train_shard_indices = list(range(n_val, n_shards))
        self.val_shard_indices = list(range(n_val))
        
        print(f"[ShardLoader] Train shards: {len(self.train_shard_indices)}, Val shards: {len(self.val_shard_indices)}")
    
    def get_loaders(
        self,
        phase: int = 1,
    ) -> Tuple[DataLoader, DataLoader]:
        """
        Get train and validation loaders for a curriculum phase.
        
        Phases:
            1: Clean data
            2: 10% dropout
            3: 20% dropout, 10% missing
            4: 30% dropout, 15% missing
            5: 40% dropout, 20% missing
        """
        degradation_map = {
            1: {"dropout_prob": 0.0, "missing_prob": 0.0},
            2: {"dropout_prob": 0.10, "missing_prob": 0.05},
            3: {"dropout_prob": 0.20, "missing_prob": 0.10},
            4: {"dropout_prob": 0.30, "missing_prob": 0.15},
            5: {"dropout_prob": 0.40, "missing_prob": 0.20},
        }
        
        degradation = degradation_map.get(phase, degradation_map[1])
        
        # Create filtered manifests
        train_manifest = dict(self.manifest)
        train_manifest["shards"] = [self.manifest["shards"][i] for i in self.train_shard_indices]
        
        val_manifest = dict(self.manifest)
        val_manifest["shards"] = [self.manifest["shards"][i] for i in self.val_shard_indices]
        
        # Create datasets
        train_dataset = ShardDataset(
            self.shard_dir, train_manifest,
            seq_len=self.seq_len,
            n_windows_per_sample=self.n_windows,
            degradation=degradation,
            shuffle_shards=True,
            shuffle_windows=True,
        )
        
        val_dataset = ShardDataset(
            self.shard_dir, val_manifest,
            seq_len=self.seq_len,
            n_windows_per_sample=self.n_windows // 2,
            degradation={"dropout_prob": 0.0, "missing_prob": 0.0},  # Clean val
            shuffle_shards=False,
            shuffle_windows=False,
        )
        
        # Create loaders
        train_loader = DataLoader(
            train_dataset,
            batch_size=self.batch_size,
            num_workers=self.num_workers,
            pin_memory=self.pin_memory,
        )
        
        val_loader = DataLoader(
            val_dataset,
            batch_size=self.batch_size,
            num_workers=self.num_workers,
            pin_memory=self.pin_memory,
        )
        
        return train_loader, val_loader


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    """Test the shard loader."""
    import argparse
    
    parser = argparse.ArgumentParser()
    parser.add_argument("--shard_dir", type=str, default="data_shards")
    parser.add_argument("--batch_size", type=int, default=8)
    args = parser.parse_args()
    
    print("Testing ShardLoader...")
    
    loader = ShardLoader(
        shard_dir=args.shard_dir,
        batch_size=args.batch_size,
        n_windows=3,
    )
    
    train_loader, val_loader = loader.get_loaders(phase=1)
    
    print(f"\nIterating through train loader...")
    for i, (X, y, routing, persona) in enumerate(train_loader):
        print(f"  Batch {i}: X={X.shape}, y={y.shape}, routing={routing.shape}")
        if i >= 2:
            break
    
    print("\nShardLoader test passed!")


if __name__ == "__main__":
    main()
